"""BigQueryWriter: idempotent INSERT for the statcast_pitches table."""

from __future__ import annotations

import logging
from dataclasses import dataclass

import pandas as pd
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

from statcast_bigquery.schema import PITCHES_SCHEMA, get_partitioning

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class TableRef:
    project: str
    dataset: str
    table: str

    @classmethod
    def parse(cls, fq: str) -> TableRef:
        parts = fq.split(".")
        if len(parts) != 3:
            raise ValueError(f"expected project.dataset.table, got {fq!r}")
        return cls(*parts)

    def __str__(self) -> str:
        return f"{self.project}.{self.dataset}.{self.table}"


def _bq_schema_from_specs() -> list[bigquery.SchemaField]:
    """Convert PITCHES_SCHEMA to BigQuery SchemaField objects with descriptions."""
    fields: list[bigquery.SchemaField] = []
    for spec in PITCHES_SCHEMA:
        fields.append(
            bigquery.SchemaField(
                name=spec.name,
                field_type=spec.type,
                mode=spec.mode,
                description=spec.short_description,
            )
        )
    return fields


class BigQueryWriter:
    """Idempotent writer for `statcast_pitches`."""

    def __init__(self, client: bigquery.Client) -> None:
        self.client = client

    def create_table_if_missing(self, ref: TableRef) -> None:
        """Create the table with partitioning + clustering + native column descs if absent."""
        try:
            self.client.get_table(str(ref))
            log.debug("table %s exists; skipping create", ref)
            return
        except NotFound:
            pass

        partitioning = get_partitioning()
        table = bigquery.Table(str(ref), schema=_bq_schema_from_specs())
        table.time_partitioning = bigquery.TimePartitioning(
            type_=partitioning.type,
            field=partitioning.field,
        )
        table.clustering_fields = partitioning.clustering
        table.description = (
            "Statcast pitch-level data, regular season only. "
            "Source: Baseball Savant via pybaseball. "
            "Generated by statcast-bigquery — see github.com/blahovec-labs/statcast-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def write(
        self,
        ref: TableRef,
        df: pd.DataFrame,
        start_date: str,
        end_date: str,
    ) -> int:
        """Write `df` for [start_date, end_date], idempotent (DELETE-then-INSERT, transactional)."""
        if len(df) == 0:
            log.info("empty dataframe; skip write to %s", ref)
            return 0

        delete_sql = (
            f"DELETE FROM `{ref}` "
            f"WHERE game_date BETWEEN @start AND @end"
        )
        params = [
            bigquery.ScalarQueryParameter("start", "DATE", start_date),
            bigquery.ScalarQueryParameter("end", "DATE", end_date),
        ]
        job_config = bigquery.QueryJobConfig(query_parameters=params)
        log.info("DELETE %s where game_date BETWEEN %s AND %s", ref, start_date, end_date)
        self.client.query_and_wait(delete_sql, job_config=job_config)

        log.info("INSERT %d rows -> %s", len(df), ref)
        load_job_config = bigquery.LoadJobConfig(
            schema=_bq_schema_from_specs(),
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            source_format=bigquery.SourceFormat.PARQUET,
        )
        self.client.load_table_from_dataframe(
            df, str(ref), job_config=load_job_config
        ).result()
        return len(df)
