"""BigQueryWriter: idempotent INSERT for the statcast_pitches table."""

from __future__ import annotations

import logging
from dataclasses import dataclass

import pandas as pd
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

from statcast_bigquery.schema import PITCHES_SCHEMA, get_partitioning

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class TableRef:
    project: str
    dataset: str
    table: str

    @classmethod
    def parse(cls, fq: str) -> TableRef:
        parts = fq.split(".")
        if len(parts) != 3:
            raise ValueError(f"expected project.dataset.table, got {fq!r}")
        return cls(*parts)

    def __str__(self) -> str:
        return f"{self.project}.{self.dataset}.{self.table}"


def _bq_schema_from_specs() -> list[bigquery.SchemaField]:
    """Convert PITCHES_SCHEMA to BigQuery SchemaField objects with descriptions."""
    fields: list[bigquery.SchemaField] = []
    for spec in PITCHES_SCHEMA:
        fields.append(
            bigquery.SchemaField(
                name=spec.name,
                field_type=spec.type,
                mode=spec.mode,
                description=spec.short_description,
            )
        )
    return fields


def _coerce_df_to_schema(df: pd.DataFrame) -> pd.DataFrame:
    """Drop unknown columns and coerce dtypes so the frame loads against PITCHES_SCHEMA.

    Baseball Savant periodically ADDS new columns to its feed (e.g. ``miss_distance``
    in 2026-06). Because ``write()`` loads the full dataframe against the explicit
    PITCHES_SCHEMA, an unknown column makes BigQuery reject the load with
    ``400 ... Cannot add fields (field: ...)`` — which previously crashed daily
    ingestion. Drop any column the schema doesn't define so the load stays stable as
    Savant evolves; log what's dropped so new fields can be added deliberately.

    Then coerce dtypes: pyarrow auto-casts numeric → numeric and dt → DATE/TIMESTAMP,
    but it does NOT auto-cast Int64/Float64 → STRING. pybaseball returns some columns
    (e.g. sv_id) as Int64 when the column is all-null, even though real values are
    strings — this fails Arrow conversion against a STRING BQ column. Force-cast
    STRING columns to pandas string dtype.
    """
    known = {spec.name for spec in PITCHES_SCHEMA}
    extra = [c for c in df.columns if c not in known]
    if extra:
        log.warning("dropping %d column(s) not in PITCHES_SCHEMA: %s", len(extra), extra)
        df = df.drop(columns=extra)
    for spec in PITCHES_SCHEMA:
        if spec.type == "STRING" and spec.name in df.columns:
            df[spec.name] = df[spec.name].astype("string")
    return df


class BigQueryWriter:
    """Idempotent writer for `statcast_pitches`."""

    def __init__(self, client: bigquery.Client) -> None:
        self.client = client

    def create_table_if_missing(self, ref: TableRef) -> None:
        """Create the table with partitioning + clustering + native column descs if absent."""
        try:
            self.client.get_table(str(ref))
            log.debug("table %s exists; skipping create", ref)
            return
        except NotFound:
            pass

        partitioning = get_partitioning()
        table = bigquery.Table(str(ref), schema=_bq_schema_from_specs())
        table.time_partitioning = bigquery.TimePartitioning(
            type_=partitioning.type,
            field=partitioning.field,
        )
        table.clustering_fields = partitioning.clustering
        table.description = (
            "Statcast pitch-level data, regular season only. "
            "Source: Baseball Savant via pybaseball. "
            "Generated by statcast-bigquery — see github.com/blahovec-labs/statcast-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def write(
        self,
        ref: TableRef,
        df: pd.DataFrame,
        start_date: str,
        end_date: str,
    ) -> int:
        """Write `df` for [start_date, end_date], idempotent (DELETE-then-INSERT, transactional)."""
        if len(df) == 0:
            log.info("empty dataframe; skip write to %s", ref)
            return 0

        delete_sql = (
            f"DELETE FROM `{ref}` "
            f"WHERE game_date BETWEEN @start AND @end"
        )
        params = [
            bigquery.ScalarQueryParameter("start", "DATE", start_date),
            bigquery.ScalarQueryParameter("end", "DATE", end_date),
        ]
        job_config = bigquery.QueryJobConfig(query_parameters=params)
        log.info("DELETE %s where game_date BETWEEN %s AND %s", ref, start_date, end_date)
        self.client.query_and_wait(delete_sql, job_config=job_config)

        log.info("INSERT %d rows -> %s", len(df), ref)
        load_job_config = bigquery.LoadJobConfig(
            schema=_bq_schema_from_specs(),
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            source_format=bigquery.SourceFormat.PARQUET,
        )
        df = _coerce_df_to_schema(df)
        self.client.load_table_from_dataframe(
            df, str(ref), job_config=load_job_config
        ).result()
        return len(df)
