"""Render PITCHES_SCHEMA + curated content into 5 formats: BQ descriptions, LLM
markdown, data-dictionary JSON, hobbyist markdown, dbt YAML."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from google.cloud import bigquery

from statcast_bigquery._version import __version__
from statcast_bigquery.docs.example_queries import EXAMPLE_QUERIES
from statcast_bigquery.docs.pitfalls import PITFALLS
from statcast_bigquery.docs.statsapi_map import STATCAST_TO_STATSAPI_MAP
from statcast_bigquery.docs.taxonomy import SEMANTIC_GROUPS
from statcast_bigquery.schema import PITCHES_SCHEMA, ColumnSpec


def render_bq_descriptions() -> list[bigquery.SchemaField]:
    """Return BigQuery SchemaField list with descriptions populated.

    Used by BigQueryWriter at table-create time and by `statcast-bigquery docs --format bq-apply`.
    """
    return [
        bigquery.SchemaField(
            name=c.name,
            field_type=c.type,
            mode=c.mode,
            description=c.short_description,
        )
        for c in PITCHES_SCHEMA
    ]


def render_data_dictionary(dataset: str, table: str) -> list[dict[str, Any]]:
    """Return JSON-serializable rows shaped like `shared_ops.data_dictionary`."""
    now = datetime.now(timezone.utc).isoformat()  # noqa: UP017
    return [
        {
            "dataset": dataset,
            "table": table,
            "column": c.name,
            "dtype": c.type,
            "description": c.short_description,
            "business_definition": c.business_definition,
            "owner": "data-eng",
            "tags": list(c.semantic_tags),
            "source_system": "baseball_savant",
            "upstream_lineage_json": (
                f'{{"library": "statcast-bigquery", '
                f'"version": "{__version__}", '
                f'"pybaseball_field": "{c.pybaseball_source_field}"}}'
            ),
            "created_at": now,
            "updated_at": now,
        }
        for c in PITCHES_SCHEMA
    ]


def render_llm_context() -> str:
    """One-file prompt-friendly markdown for LLM agents."""
    parts: list[str] = ["# Statcast for LLMs", ""]
    parts.append(f"_Generated by statcast-bigquery v{__version__}._\n")
    parts.append(
        "This document describes the `statcast_pitches` table — pitch-level Statcast data "
        "ingested via pybaseball. Use it as system-prompt context when generating SQL.\n"
    )

    parts.append("## Column reference\n")
    by_group = _columns_by_group()
    for group, label in SEMANTIC_GROUPS.items():
        cols = by_group.get(group, [])
        if not cols:
            continue
        parts.append(f"### {group} — {label}\n")
        for c in cols:
            parts.append(f"- **`{c.name}`** ({c.type}): {c.business_definition}")
            if c.gotchas:
                parts.append(f"  - Gotchas: {'; '.join(c.gotchas)}")
        parts.append("")

    parts.append("## Pitfalls\n")
    for p in PITFALLS:
        parts.append(f"- **{p.summary}**  \n  {p.explanation}")
    parts.append("")

    parts.append("## Example queries\n")
    for q in EXAMPLE_QUERIES:
        parts.append(f"### {q.title}\n")
        parts.append(f"_{q.question}_\n")
        parts.append("```sql")
        parts.append(q.sql)
        parts.append("```\n")
        if q.notes:
            parts.append(f"Notes: {q.notes}\n")

    parts.append("## Statcast → statsapi cross-reference\n")
    parts.append("| Statcast column | statsapi equivalent |")
    parts.append("|---|---|")
    for k, v in sorted(STATCAST_TO_STATSAPI_MAP.items()):
        parts.append(f"| `{k}` | {v if v else '_(none)_'} |")
    parts.append("")

    return "\n".join(parts)


def render_markdown() -> str:
    """Hobbyist-friendly schema reference markdown — auto-generated `docs/schema.md`."""
    parts: list[str] = ["# statcast_pitches schema\n"]
    parts.append(f"_Generated by statcast-bigquery v{__version__}._\n")
    parts.append("Pitch-level Statcast data, regular season only.\n")

    by_group = _columns_by_group()
    for group, label in SEMANTIC_GROUPS.items():
        cols = by_group.get(group, [])
        if not cols:
            continue
        parts.append(f"## {group}\n")
        parts.append(f"_{label}_\n")
        parts.append("| Column | Type | Mode | Description |")
        parts.append("|---|---|---|---|")
        for c in cols:
            parts.append(f"| `{c.name}` | {c.type} | {c.mode} | {c.short_description} |")
        parts.append("")

    return "\n".join(parts)


def render_dbt_yaml(model_name: str = "statcast_pitches") -> str:
    """dbt model YAML with column descriptions and basic tests for required columns."""
    parts: list[str] = ["version: 2\n", "models:"]
    parts.append(f"  - name: {model_name}")
    parts.append("    description: |")
    parts.append("      Pitch-level Statcast data ingested via statcast-bigquery.")
    parts.append("      Source: Baseball Savant via pybaseball.")
    parts.append("    columns:")
    for c in PITCHES_SCHEMA:
        parts.append(f"      - name: {c.name}")
        parts.append("        description: |")
        parts.append(f"          {c.short_description}")
        if c.mode == "REQUIRED":
            parts.append("        tests:")
            parts.append("          - not_null")
    return "\n".join(parts) + "\n"


def apply_data_dictionary(
    *,
    client: bigquery.Client,
    dictionary_table: str,
    dataset: str,
    table: str,
) -> int:
    """Atomically replace the data_dictionary rows for (dataset, table).

    Wraps DELETE + INSERT in a single BEGIN TRANSACTION ... COMMIT TRANSACTION
    multi-statement query so the table is never observed in a half-replaced state.

    Returns the number of rows inserted.
    """
    rows = render_data_dictionary(dataset=dataset, table=table)
    if not rows:
        return 0

    # Build VALUES tuples inline. Row volume ~120 per table; well within DML limits.
    # Strings are escaped via repr-then-strip; tags is BQ array literal.
    def _str(s: str | None) -> str:
        if s is None:
            return "NULL"
        # BQ Standard SQL accepts backslash-escaped string literals.
        # Escape backslashes first, then single quotes, to avoid double-processing.
        return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"

    def _tags(t: list[str]) -> str:
        return "[" + ", ".join(_str(x) for x in t) + "]"

    values_lines: list[str] = []
    for r in rows:
        values_lines.append(
            "("
            f"{_str(r['dataset'])}, {_str(r['table'])}, {_str(r['column'])}, "
            f"{_str(r['dtype'])}, {_str(r['description'])}, "
            f"{_str(r['business_definition'])}, {_str(r['owner'])}, "
            f"{_tags(r['tags'])}, {_str(r['source_system'])}, "
            f"{_str(r['upstream_lineage_json'])}, "
            f"TIMESTAMP({_str(r['created_at'])}), TIMESTAMP({_str(r['updated_at'])})"
            ")"
        )
    values_sql = ",\n  ".join(values_lines)

    sql = (
        "BEGIN TRANSACTION;\n"
        f"DELETE FROM `{dictionary_table}` "
        f"WHERE dataset=@dataset AND table=@table;\n"
        f"INSERT INTO `{dictionary_table}` "
        "(dataset, `table`, column, dtype, description, business_definition, "
        "owner, tags, source_system, upstream_lineage_json, created_at, updated_at) "
        f"VALUES\n  {values_sql};\n"
        "COMMIT TRANSACTION;"
    )
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("dataset", "STRING", dataset),
            bigquery.ScalarQueryParameter("table", "STRING", table),
        ]
    )
    client.query_and_wait(sql, job_config=job_config)
    return len(rows)


def _columns_by_group() -> dict[str, list[ColumnSpec]]:
    """Group columns by their first semantic_tag (canonical group)."""
    out: dict[str, list[ColumnSpec]] = {}
    for c in PITCHES_SCHEMA:
        if not c.semantic_tags:
            continue
        out.setdefault(c.semantic_tags[0], []).append(c)
    return out
