"""Render PITCHES_SCHEMA + curated content into 5 formats: BQ descriptions, LLM
markdown, data-dictionary JSON, hobbyist markdown, dbt YAML."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from google.cloud import bigquery

from statcast_bigquery._version import __version__
from statcast_bigquery.docs.example_queries import EXAMPLE_QUERIES
from statcast_bigquery.docs.pitfalls import PITFALLS
from statcast_bigquery.docs.statsapi_map import STATCAST_TO_STATSAPI_MAP
from statcast_bigquery.docs.taxonomy import SEMANTIC_GROUPS
from statcast_bigquery.schema import PITCHES_SCHEMA, ColumnSpec


def render_bq_descriptions() -> list[bigquery.SchemaField]:
    """Return BigQuery SchemaField list with descriptions populated.

    Used by BigQueryWriter at table-create time and by `statcast-bigquery docs --format bq-apply`.
    """
    return [
        bigquery.SchemaField(
            name=c.name,
            field_type=c.type,
            mode=c.mode,
            description=c.short_description,
        )
        for c in PITCHES_SCHEMA
    ]


def render_data_dictionary(dataset: str, table: str) -> list[dict[str, Any]]:
    """Return JSON-serializable rows shaped like `shared_ops.data_dictionary`."""
    now = datetime.now(timezone.utc).isoformat()  # noqa: UP017
    return [
        {
            "dataset": dataset,
            "table": table,
            "column": c.name,
            "dtype": c.type,
            "description": c.short_description,
            "business_definition": c.business_definition,
            "owner": "data-eng",
            "tags": list(c.semantic_tags),
            "source_system": "baseball_savant",
            "upstream_lineage_json": (
                f'{{"library": "statcast-bigquery", '
                f'"version": "{__version__}", '
                f'"pybaseball_field": "{c.pybaseball_source_field}"}}'
            ),
            "created_at": now,
            "updated_at": now,
        }
        for c in PITCHES_SCHEMA
    ]


def render_llm_context() -> str:
    """One-file prompt-friendly markdown for LLM agents."""
    parts: list[str] = ["# Statcast for LLMs", ""]
    parts.append(f"_Generated by statcast-bigquery v{__version__}._\n")
    parts.append(
        "This document describes the `statcast_pitches` table — pitch-level Statcast data "
        "ingested via pybaseball. Use it as system-prompt context when generating SQL.\n"
    )

    parts.append("## Column reference\n")
    by_group = _columns_by_group()
    for group, label in SEMANTIC_GROUPS.items():
        cols = by_group.get(group, [])
        if not cols:
            continue
        parts.append(f"### {group} — {label}\n")
        for c in cols:
            parts.append(f"- **`{c.name}`** ({c.type}): {c.business_definition}")
            if c.gotchas:
                parts.append(f"  - Gotchas: {'; '.join(c.gotchas)}")
        parts.append("")

    parts.append("## Pitfalls\n")
    for p in PITFALLS:
        parts.append(f"- **{p.summary}**  \n  {p.explanation}")
    parts.append("")

    parts.append("## Example queries\n")
    for q in EXAMPLE_QUERIES:
        parts.append(f"### {q.title}\n")
        parts.append(f"_{q.question}_\n")
        parts.append("```sql")
        parts.append(q.sql)
        parts.append("```\n")
        if q.notes:
            parts.append(f"Notes: {q.notes}\n")

    parts.append("## Statcast → statsapi cross-reference\n")
    parts.append("| Statcast column | statsapi equivalent |")
    parts.append("|---|---|")
    for k, v in sorted(STATCAST_TO_STATSAPI_MAP.items()):
        parts.append(f"| `{k}` | {v if v else '_(none)_'} |")
    parts.append("")

    return "\n".join(parts)


def render_markdown() -> str:
    """Hobbyist-friendly schema reference markdown — auto-generated `docs/schema.md`."""
    parts: list[str] = ["# statcast_pitches schema\n"]
    parts.append(f"_Generated by statcast-bigquery v{__version__}._\n")
    parts.append("Pitch-level Statcast data, regular season only.\n")

    by_group = _columns_by_group()
    for group, label in SEMANTIC_GROUPS.items():
        cols = by_group.get(group, [])
        if not cols:
            continue
        parts.append(f"## {group}\n")
        parts.append(f"_{label}_\n")
        parts.append("| Column | Type | Mode | Description |")
        parts.append("|---|---|---|---|")
        for c in cols:
            parts.append(f"| `{c.name}` | {c.type} | {c.mode} | {c.short_description} |")
        parts.append("")

    return "\n".join(parts)


def render_dbt_yaml(model_name: str = "statcast_pitches") -> str:
    """dbt model YAML with column descriptions and basic tests for required columns."""
    parts: list[str] = ["version: 2\n", "models:"]
    parts.append(f"  - name: {model_name}")
    parts.append("    description: |")
    parts.append("      Pitch-level Statcast data ingested via statcast-bigquery.")
    parts.append("      Source: Baseball Savant via pybaseball.")
    parts.append("    columns:")
    for c in PITCHES_SCHEMA:
        parts.append(f"      - name: {c.name}")
        parts.append("        description: |")
        parts.append(f"          {c.short_description}")
        if c.mode == "REQUIRED":
            parts.append("        tests:")
            parts.append("          - not_null")
    return "\n".join(parts) + "\n"


def _columns_by_group() -> dict[str, list[ColumnSpec]]:
    """Group columns by their first semantic_tag (canonical group)."""
    out: dict[str, list[ColumnSpec]] = {}
    for c in PITCHES_SCHEMA:
        if not c.semantic_tags:
            continue
        out.setdefault(c.semantic_tags[0], []).append(c)
    return out
