"""UmpireWriter: idempotent DELETE+INSERT for game_umpires.

Mirror of BigQueryWriter for the pitches table — same idempotent pattern keyed
on game_date so re-runs of an overlapping window safely replace.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import pandas as pd
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

from statcast_bigquery.umpires.schema import (
    GAME_UMPIRES_SCHEMA,
    get_umpires_partitioning,
)

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class UmpireTableRef:
    project: str
    dataset: str
    table: str

    @classmethod
    def parse(cls, fq: str) -> UmpireTableRef:
        parts = fq.split(".")
        if len(parts) != 3:
            raise ValueError(f"expected project.dataset.table, got {fq!r}")
        return cls(*parts)

    def __str__(self) -> str:
        return f"{self.project}.{self.dataset}.{self.table}"


def _bq_schema_from_umpire_specs() -> list[bigquery.SchemaField]:
    fields: list[bigquery.SchemaField] = []
    for spec in GAME_UMPIRES_SCHEMA:
        fields.append(
            bigquery.SchemaField(
                name=spec.name,
                field_type=spec.type,
                mode=spec.mode,
                description=spec.short_description,
            )
        )
    return fields


class UmpireWriter:
    """Idempotent writer for `game_umpires`."""

    def __init__(self, client: bigquery.Client) -> None:
        self.client = client

    def create_table_if_missing(self, ref: UmpireTableRef) -> None:
        try:
            self.client.get_table(str(ref))
            log.debug("table %s exists; skipping create", ref)
            return
        except NotFound:
            pass
        partitioning = get_umpires_partitioning()
        table = bigquery.Table(str(ref), schema=_bq_schema_from_umpire_specs())
        table.time_partitioning = bigquery.TimePartitioning(
            type_=partitioning.type, field=partitioning.field,
        )
        table.clustering_fields = partitioning.clustering
        table.description = (
            "MLB umpire crew per game, sourced from statsapi boxscore officials. "
            "Generated by statcast-bigquery — see github.com/blahovec-labs/statcast-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def write(
        self,
        ref: UmpireTableRef,
        df: pd.DataFrame,
        start_date: str,
        end_date: str,
    ) -> int:
        """Idempotent DELETE+INSERT for [start_date, end_date]."""
        if len(df) == 0:
            log.info("empty umpires dataframe; skip write to %s", ref)
            return 0

        delete_sql = (
            f"DELETE FROM `{ref}` WHERE game_date BETWEEN @start AND @end"
        )
        params = [
            bigquery.ScalarQueryParameter("start", "DATE", start_date),
            bigquery.ScalarQueryParameter("end", "DATE", end_date),
        ]
        log.info("DELETE %s where game_date BETWEEN %s AND %s",
                 ref, start_date, end_date)
        self.client.query_and_wait(
            delete_sql, job_config=bigquery.QueryJobConfig(query_parameters=params)
        )

        log.info("INSERT %d umpire rows -> %s", len(df), ref)
        load_job_config = bigquery.LoadJobConfig(
            schema=_bq_schema_from_umpire_specs(),
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            source_format=bigquery.SourceFormat.PARQUET,
        )
        self.client.load_table_from_dataframe(
            df, str(ref), job_config=load_job_config
        ).result()
        return len(df)
