"""GameWriter: idempotent DELETE+INSERT for the games table.

Keyed on season — re-running the writer for a season replaces all rows
for that season. This is the right semantic because the schedule is
fundamentally one entity per season: probable pitchers update, statuses
change, scores fill in. Wholesale replacement keeps the table consistent
without needing per-game UPSERT logic.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from dataclasses import dataclass

import pandas as pd
from google.cloud import bigquery
from google.cloud.exceptions import NotFound

from statcast_bigquery.games.schema import GAMES_SCHEMA, get_games_partitioning

log = logging.getLogger(__name__)


@dataclass(frozen=True)
class GamesTableRef:
    project: str
    dataset: str
    table: str

    @classmethod
    def parse(cls, fq: str) -> GamesTableRef:
        parts = fq.split(".")
        if len(parts) != 3:
            raise ValueError(f"expected project.dataset.table, got {fq!r}")
        return cls(*parts)

    def __str__(self) -> str:
        return f"{self.project}.{self.dataset}.{self.table}"


def _bq_schema_from_games_specs() -> list[bigquery.SchemaField]:
    fields: list[bigquery.SchemaField] = []
    for spec in GAMES_SCHEMA:
        fields.append(
            bigquery.SchemaField(
                name=spec.name,
                field_type=spec.type,
                mode=spec.mode,
                description=spec.short_description,
            )
        )
    return fields


class GameWriter:
    """Idempotent writer for the games table."""

    def __init__(self, client: bigquery.Client) -> None:
        self.client = client

    def create_table_if_missing(self, ref: GamesTableRef) -> None:
        try:
            self.client.get_table(str(ref))
            log.debug("table %s exists; skipping create", ref)
            return
        except NotFound:
            pass
        partitioning = get_games_partitioning()
        table = bigquery.Table(str(ref), schema=_bq_schema_from_games_specs())
        table.time_partitioning = bigquery.TimePartitioning(
            type_=partitioning.type, field=partitioning.field,
        )
        table.clustering_fields = partitioning.clustering
        table.description = (
            "MLB game schedule (regular + postseason). Sourced from statsapi "
            "/api/v1/schedule. Generated by statcast-bigquery — see "
            "github.com/blahovec-labs/statcast-bigquery."
        )
        self.client.create_table(table)
        log.info("created table %s", ref)

    def write(
        self,
        ref: GamesTableRef,
        df: pd.DataFrame,
        seasons: Iterable[int],
    ) -> int:
        """Replace all rows for the given seasons with df.

        Caller passes the seasons covered by df explicitly (instead of inferring
        from the dataframe) so a successful DELETE for an empty fetch still
        clears the slate intentionally.
        """
        seasons_list = sorted(set(int(s) for s in seasons))
        if not seasons_list:
            log.info("no seasons specified; skip games write")
            return 0

        season_array = ",".join(str(s) for s in seasons_list)
        delete_sql = f"DELETE FROM `{ref}` WHERE season IN ({season_array})"
        log.info("DELETE %s where season IN (%s)", ref, season_array)
        self.client.query_and_wait(delete_sql)

        if len(df) == 0:
            log.info("empty games dataframe for seasons %s; DELETE-only", season_array)
            return 0

        log.info("INSERT %d games -> %s", len(df), ref)
        load_job_config = bigquery.LoadJobConfig(
            schema=_bq_schema_from_games_specs(),
            write_disposition=bigquery.WriteDisposition.WRITE_APPEND,
            source_format=bigquery.SourceFormat.PARQUET,
        )
        # pyarrow stricter on dtypes when target is INT64 NULLABLE; cast.
        for col in ("final_home_score", "final_away_score", "probable_home_pitcher_id",
                    "probable_away_pitcher_id", "venue_id", "game_number"):
            if col in df.columns:
                df[col] = df[col].astype("Int64")

        self.client.load_table_from_dataframe(
            df, str(ref), job_config=load_job_config
        ).result()
        return len(df)
